[package]
name = "dialogue_bot"
version = "0.1.0"
authors = ["Temirkhan Myrzamadi <hirrolot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
tokio = "0.2.9"
pretty_env_logger = "0.4.0"
futures = "0.3.5"
smart-default = "0.6.0"
derive_more = "0.99.9"
teloxide = { path = "../../" }
teloxide-macros = { path = "../../../teloxide-macros" }
#teloxide-macros = { git = "http://github.com/teloxide/teloxide-macros", branch = "master" }

[profile.release]
lto = true