[package]
name = "async-telegram-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = { version = "0.3.0-alpha.14", features = ["compat"] }
reqwest = "0.9.20"
serde_json = "1.0.39"
serde = {version = "1.0.92", features = ["derive"] }
lazy_static = "1.3"
apply = "0.2.2"
derive_more = "0.15.0"
tokio = "0.1"
bytes = "0.4.12"