[build] 
command = "rustup install nightly-2022-02-02 --profile minimal && cargo +nightly doc --all-features --no-deps -Zunstable-options -Zrustdoc-scrape-examples=examples && cp -r target/doc _netlify_out"
publish = "_netlify_out" 

[build.environment] 
RUSTFLAGS="--cfg dep_docsrs"
# FIXME: Add back "-Znormalize-docs" when https://github.com/rust-lang/rust/issues/93703 is fixed
RUSTDOCFLAGS= "--cfg docsrs" 

[[redirects]]
from = "/" 
to = "/teloxide"
