[package]
name = "buttons"
version = "0.1.0"
edition = "2018"

[dependencies]
teloxide = { path = "../../", features = ["macros"] }

tokio = { version =  "1.3", features = ["rt-multi-thread", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
