on: [push, pull_request]

name: Continuous integration

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  stable-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test --all-features
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the examples
        run: cd examples && bash test_examples.sh
